# Generated by Django 5.2.4 on 2025-08-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('phuahtu', models.CharField(max_length=255)),
                ('satu', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='thlalak/')),
            ],
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.TextField()),
            ],
        ),
    ]
