# Generated by Django 5.2.5 on 2025-08-10 14:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
