# Generated by Django 5.2.5 on 2025-08-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0002_alter_data_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
