# Generated by Django 5.2.5 on 2025-08-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0004_viewtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
