# Generated by Django 5.2.5 on 2025-08-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0005_alter_data_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
