# Generated by Django 5.2.5 on 2025-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hla', '0007_alter_data_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
